language: python
python:
    - "3.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    # ESP8266
    - SCRIPT=platformioSingle EXAMPLE_NAME=TelegramChat EXAMPLE_FOLDER=/ BOARDTYPE=ESP8266 BOARD=d1_mini

install:
    - pip install -U platformio
    - platformio update
    #
    # Libraries from PlatformIO Library Registry:
    # http://platformio.org/lib/show/64/ArduinoJson
    # http://platformio.org/lib/show/89/PubSubClient
    # http://platformio.org/lib/show/1262/UniversalTelegramBot
    - platformio lib -g install 64 89 1262

script:
    - scripts/travis/$SCRIPT.sh
